version: 2
updates:
  - package-ecosystem: gomod
    directory: /cli
    schedule:
      interval: weekly
    groups:
      cli-go-dependencies:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-go-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /frontend/web
    schedule:
      interval: weekly
    groups:
      web-production-dependencies:
        dependency-type: production
        patterns: ["*"]
      web-development-dependencies:
        dependency-type: development
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
