// Package hook contains the hook event handlers for the cxt hook subcommand (domain model, capture path).
//
// Usage: cxt hook --provider <claude|codex> --event <Name>
//
// Event-specific actions (capture path):
//
//	SessionStart(claude/codex):   CaptureCoordinator.MarkBaseline (no commit)
//	Stop(claude/codex):           CaptureCoordinator.RequestCapture(debounce=true)
//	SessionEnd(claude):           CaptureCoordinator.RequestCapture(force=true) — force flush
//	UserPromptSubmit(codex):      CaptureCoordinator.MarkTurn (no commit)
//
// Safety Contract (invariants, capture path):
//   - Always exit 0 (errors reported only to stderr — cmd/cxt hook branch ensures)
//   - Terminate within 10 seconds (hooks.json timeout:10) — double defense with 8-second context timeout
//   - Read original session file as read-only
//   - ErrNoActiveSession → no-op silently
package hook

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"syscall"
	"time"

	"github.com/wnsdy95/cxthub/cli/internal/adapters/capture"
	"github.com/wnsdy95/cxthub/cli/internal/adapters/remotecfg"
	"github.com/wnsdy95/cxthub/cli/internal/domain"
)

// Handler is the hook event handler. Keep it thin (capture path) —
// parse stdin and classify events, delegate core logic to CaptureCoordinator.
type Handler struct {
	coord  *capture.CaptureCoordinator
	stdin  io.Reader // for testing. nil means os.Stdin (no read from terminal)
	stdout io.Writer // for testing. nil means os.Stdout (additionalContext JSON emission channel)
}

// NewHandler creates a Handler and injects CaptureCoordinator.
func NewHandler(coord *capture.CaptureCoordinator) *Handler {
	return &Handler{coord: coord}
}

// hookPayload contains the known keys from provider hook stdin JSON.
type hookPayload struct {
	SessionID      string `json:"session_id"`
	TranscriptPath string `json:"transcript_path"` // claude
	RolloutPath    string `json:"rollout_path"`    // Codex hint; falls back to discovery when absent
	Cwd            string `json:"cwd"`
	Prompt         string `json:"prompt"` // UserPromptSubmit
}

// readPayload attempts best-effort parsing of stdin JSON. If not from a terminal (not a pipe),
// it reads only known keys even if the schema differs — failure results in an empty payload (fallback), not an error.
func (h *Handler) readPayload() hookPayload {
	var p hookPayload
	r := h.stdin
	if r == nil {
		fi, err := os.Stdin.Stat()
		if err != nil || fi.Mode()&os.ModeCharDevice != 0 {
			return p
		}
		r = os.Stdin
	}
	b, err := io.ReadAll(io.LimitReader(r, 256<<10))
	if err != nil {
		return p
	}
	_ = json.Unmarshal(b, &p)
	return p
}

// Run handles hook events. Unknown events are no-op (fail-open).
// Return errors are reported only to stderr by the caller (cmd/cxt) and exit 0 is maintained.
func (h *Handler) Run(provider domain.ProviderKind, event string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer cancel()

	p := h.readPayload()
	cwd := p.Cwd
	if cwd == "" {
		if wd, err := os.Getwd(); err == nil {
			cwd = wd
		}
	}
	path := p.TranscriptPath
	if path == "" {
		path = p.RolloutPath
	}

	switch event {
	case "SessionStart":
		err := h.coord.MarkBaseline(ctx, provider, cwd, path)
		h.emitBriefing(event, cwd) // pull after new/restart session — remaining briefing delivery (secondary channel)
		return err
	case "UserPromptSubmit":
		err := h.coord.MarkTurn(ctx, provider, cwd, p.Prompt)
		h.emitBriefing(event, cwd) // team member context injection briefing for next turn (primary channel)
		return err
	case "Stop":
		captured, err := h.coord.RequestCapture(ctx, provider, cwd, path, true, false)
		if captured {
			spawnPendingSync(cwd)
		}
		return err
	case "SessionEnd":
		captured, err := h.coord.RequestCapture(ctx, provider, cwd, path, false, true)
		if captured {
			spawnPendingSync(cwd)
		}
		return err
	default:
		return nil
	}
}

// emitBriefing consumes a team member context injection briefing (.cxt/briefing.json — generated by git pull) and emits it as JSON to stdout via hookSpecificOutput.additionalContext.
// This output is not visible to users but is passed only to the model. Empirically verified (0.143):
// The codex binary contains additionalContext/HookOutputEntry/EventName (sessionStart, userPromptSubmit, etc.) — confirmed as compatible with the Claude Code hook schema.
func (h *Handler) emitBriefing(event, cwd string) {
	text, ok := capture.ConsumeBriefing(cwd)
	if !ok {
		return
	}
	out := map[string]interface{}{
		"hookSpecificOutput": map[string]interface{}{
			"hookEventName":     event,
			"additionalContext": text,
		},
	}
	b, err := json.Marshal(out)
	if err != nil {
		return
	}
	w := h.stdout
	if w == nil {
		w = os.Stdout
	}
	_, _ = fmt.Fprintln(w, string(b))
}

// spawnPendingSync spawns a detached helper to reflect the in-progress context pointer to the server.
// The hook process is latency-sensitive and does not directly use the network.
// A separate process performs best-effort work, and later capture or push
// reconciliation recovers failures.
func spawnPendingSync(cwd string) {
	if _, ok := remotecfg.Origin(cwd); !ok && os.Getenv("CXT_REMOTE") == "" {
		return
	}
	exe, err := os.Executable()
	if err != nil {
		return
	}
	cmd := exec.Command(exe, "git-hook", "pending-sync")
	cmd.Dir = cwd
	cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	_ = cmd.Start()
}
